name: Rust Build and Run

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      BY_MARKET: ${{ secrets.BY_MARKET }}
      RETURN: ${{ secrets.RETURN }}
      UK_LOCALISATION: ${{ secrets.UK_LOCALISATION }}
      ROLL_UP: ${{ secrets.ROLL_UP }}
      MARKET_TYPES: ${{ secrets.MARKET_TYPES }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if environment variables are set
        run: |
          echo "BASE_URL is set: $([[ -z "${BASE_URL}" ]] && echo "false" || echo "true")"
          echo "BY_MARKET is set: $([[ -z "${BY_MARKET}" ]] && echo "false" || echo "true")"
          echo "RETURN is set: $([[ -z "${RETURN}" ]] && echo "false" || echo "true")"
          echo "UK_LOCALISATION is set: $([[ -z "${UK_LOCALISATION}" ]] && echo "false" || echo "true")"
          echo "ROLL_UP is set: $([[ -z "${ROLL_UP}" ]] && echo "false" || echo "true")"
          echo "MARKET_TYPES is set: $([[ -z "${MARKET_TYPES}" ]] && echo "false" || echo "true")"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build

      - name: Run project
        run: cargo run
